# This is a basic workflow to help you get started with Actions

name: docker build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker building
        run: |
          docker-compose up -d --build -site

